<?php

/**
 * Implements hook_preprocess_block().
 */
function dorion_preprocess_page(&$variables) {
//  $theme = \Drupal::theme()->getActiveTheme()->getName();
//  foreach (RegionSettings::getNavbarRegions($theme) as $region_id => $title) {
//    if (empty($variables['page'][$region_id])) {
//      continue;
//    }
//    RegionSettings::setPlacement($variables['page'][$region_id]);
//    RegionSettings::setNavbarCollapsible($variables['page'][$region_id]);
//  }

}
